---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Screenshot from 2018-03-01 17-45-16/Screenshot from 2018-03-01 17-45-16.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/148374/articles/283882/master/file/figures/Screenshot%20from%202018-03-01%2017-45-16/Screenshot%20from%202018-03-01%2017-45-16.png"
    folder_url: "/users/148374/articles/283882/master/folder/figures/Screenshot from
      2018-03-01 17-45-16"
